[package]
name = "chip_bert"
version = "0.1.0"
authors = ["Weston Carlson <wcarlson@digitalocean.com>"]
edition = "2018"

[dependencies]
structopt = "0.3.1"
rand = "0.7"

[dependencies.sdl2]
version = "0.32.2"